# Header
menu:
  Home: /
  Archives: /archives
  About: /about/index.html
rss:
github: https://github.com/ppoffice/hexo-theme-alex

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: left
widgets:
- category
- archive
- recent_posts
- tag
- tagcloud
- links

# Links
links:
  Hexo: http://hexo.io

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

# 多说账号
duoshuo_shortname: malcolmyu
